; PlatformIO Project Configuration File
; ESP32 Devboard - Sensor + ESP-NOW broadcaster

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = no_ota.csv
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/RTClib@^2.1.4
    bblanchon/ArduinoJson@^7.4.2
